opensibi/urls.py
from project.views import *
from django.contrib import admin
from django.urls import path, include
from user.views import *
from monitor.views import *
from myo.views import myo
from leap.views import leap
from voice.views import voice
from rest_framework import routers

router = routers.DefaultRouter()
router.register('user', UserViewset)


urlpatterns = [
    path('api/', include(router.urls)),
    path('admin', index),
    path('monitor/', monitor),
    path('myo', myo),
    path('project', projects),
    path('test', test),
    path('getToken/<int:id>', getToken),
    path('leap', leap),
    path('voice', voice),
    path('auth', auth),
    path('viewLogin', viewLogin),
    path('viewLoginUser', viewLoginUser),
    path('viewRegister', viewRegister),
    path('viewRegisterUser', viewRegisterUser),
    path('viewLogout', viewLogout),
    path('viewLogoutUser', viewLogoutUser),
    path('', dashboardUser),
    path('login', login),
    path('loginUser', loginUser),
    path('register', register),
    path('registerUser', registerUser),
    path('logoutUser', viewLogoutUser),  
    path('logout', logoutApi),   
]

project/models.py
from django.db import models
from datetime import datetime
from user.models import Users

class Project(models.Model):
    id = models.BigAutoField(primary_key=True)
    id_user = models.ForeignKey(Users, on_delete=models.CASCADE)
    project_name = models.CharField(max_length=200, null=True)
    created_at = models.DateTimeField(default=datetime.utcnow)
    updated_at = models.DateTimeField(default=datetime.utcnow)

    class Meta:
        db_table = 'project'

class Token(models.Model):
    id = models.BigAutoField(primary_key=True)
    token_user = models.CharField(max_length=200, null=True)
    ip = models.CharField(max_length=200, null=True)
    status = models.CharField(max_length=200, null=True)
    created_at = models.DateTimeField(default=datetime.utcnow)
    updated_at = models.DateTimeField(default=datetime.utcnow)

    class Meta:
        db_table = 'token'

project/forms.py
from django.forms import ModelForm
from user.models import Users
from project.models import Project

class formProject(ModelForm):
    class Meta:
        model = Project
        fields = ['project_name']

class formUsers(ModelForm):
    class Meta:
        model = Users
        fields = ['name','email','password']
        

project/views.py
from monitor.transformer import transform
from sklearn.neighbors import KNeighborsClassifier
from django.db import connection
import numpy as np
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponse
from user.models import Users
from project.forms import formUsers,formProject
from opensibi.response import Response
from opensibi.middleware import *
from project.models import *
from django.contrib.auth.forms import AuthenticationForm
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator
from project import transformer


@csrf_exempt
def projects(request):
    project = Project()
    project.project_name = request.POST.get('project_name')
    project.id_user_id = request.session['user_id']
    project.save()
    return redirect("/")


@csrf_exempt
def getToken(request, id):
    project = Project.objects.filter(id=id).first()
    project = transformer.singleTransform(project)
    jwt = JWTAuth()
    generateToken = jwt.encode({"id": project['id'], "id_user": project['id_user'], "project_name": project['project_name']})
    token = Token.objects.filter(token_user=generateToken).first()
    if not token:
        token = Token()
        token.token_user = generateToken
        token.status = "unused"
        token.save()
    else:
        return Response.ok(generateToken, message='token already generated')
    return Response.ok(generateToken, message="Success")


@csrf_exempt 
def loginUser(request):
    form = formUsers()
    if request.method == 'POST':
        m = Users.objects.filter(email=request.POST['email']).first()
        print("if 1")
    if not m:
        return render(request, "loginUser.html", {'warning': "e-mail not registered ", 'form': form})
    if m.password == request.POST['password']:
        print("masuk if2")
        request.session['user_id'] = m.id
        return redirect("/")
    else:
        return render(request, "loginUser.html", {'warning': "password didn't match.", 'form': form})

@csrf_exempt 
def register(request):
    user = Users()
    users = formUsers()
    m = Users.objects.filter(email=request.POST['email'])

    if m:
        return render(request, "register.html", {'warning': "E-mail already registered", 'form': users})
    
    else:
        user = Users()
        user.name = request.POST['name']
        user.email = request.POST['email']
        user.password = request.POST['password']
        user.save()
        return render(request, "login.html", {'warning1': "registered successfully", 'form': users})

@csrf_exempt 
def registerUser(request):
    user = Users()
    users = formUsers()
    m = Users.objects.filter(email=request.POST['email'])
    if m:
        return render(request, "registerUser.html", {'warning': "E-mail already registered", 'form': users})
    else:
        user = Users()
        user.name = request.POST['name']
        user.email = request.POST['email']
        user.password = request.POST['password']
        user.save()
        return render(request, "loginUser.html", {'warning1': "registered successfully", 'form': users})

@csrf_exempt 
def viewLogin(request):
    users = formUsers()
    return render(request, 'login.html', {'form': users})

@csrf_exempt 
def viewLoginUser(request):
    users = formUsers()
    return render(request, 'loginUser.html', {'form': users})

@csrf_exempt 
def viewRegister(request):
    users = formUsers()
    return render(request, 'register.html', {'form': users})

@csrf_exempt 
def viewRegisterUser(request):
    users = formUsers()
    return render(request, 'registerUser.html', {'form': users})

@csrf_exempt
def viewLogout(request):
    users = formUsers() 
    try:
        del request.session['user_id']
    except KeyError:
        pass
    return redirect("/viewLogin")

@csrf_exempt
def viewLogoutUser(request):
    users = formUsers() 
    try:
        del request.session['user_id']
    except KeyError:
        pass
    return redirect("/viewLoginUser")

@csrf_exempt
def index(request):
    if 'user_id' not in request.session:
        return redirect("/viewLogin")


    users = Users.objects.all()
    totalUser = Users.objects.all().count()
    leap = Project.objects.filter(project_name='leap').count()
    dataLeap = Project.objects.filter(project_name='leap').select_related('id_user')
    dataMyo = Project.objects.filter(project_name='myo').select_related('id_user')
    dataVoice = Project.objects.filter(project_name='voice').select_related('id_user')
    myo = Project.objects.filter(project_name='myo').count()
    voice = Project.objects.filter(project_name='voice').count()
    return render(request, 'dashboard.html', {
                                              'users': users, 
                                              'myo': myo, 
                                              'leap': leap, 
                                              'voice': voice, 
                                              'total': totalUser, 
                                              'dataleaps': dataLeap,
                                              'datamyos': dataMyo,
                                              'datavoices': dataVoice })
@csrf_exempt
def dashboardUser(request):
    if 'user_id' not in request.session:
        return redirect("/viewLoginUser")

    form = formProject()
    project = Project.objects.filter(id_user_id=request.session['user_id'])   
    return render(request, 'dashboardUser.html', {'projects': project, 'form': form})

@csrf_exempt
def test(request):
    project = Project.objects.filter(project_name='leap')
    project = transformer.transform(project)
    return Response.ok(project, message='token already generated')
    
    

project/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  
  <title>{% block title %}{% endblock %}</title>

  <!-- Custom fonts for this template-->
  <link href="/static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

  <!-- Page level plugin CSS-->
  <link href="/static/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">

  {% block links %}
  {% endblock %}

</head>

{% block body %}
{% endblock %}

</html>

project/templates/dashboardUser.html
{% extends "base.html" %}

{% block title %}Dashboard User{% endblock %}

{% block links %}
  <!-- Custom styles for this template-->
  <link href="/static/css/sb-admin.css" rel="stylesheet">
{% endblock %}
{% block body %}
<script>
 
  </script>
<body id="page-top">

  <nav class="navbar navbar-expand navbar-dark bg-primary static-top">

    <a class="navbar-brand mr-1" href="">OpenSIBI</a>

    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
      <i class="fas fa-bars"></i>
    </button>

    <!-- Navbar Search -->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
    </form>

    <!-- Navbar -->
    <ul class="navbar-nav ml-auto ml-md-0">
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        </a>
      </li>
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        </a>
      </li>
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user-circle fa-fw"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="#"></a>
          <a class="dropdown-item" href="#"></a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
        </div>
      </li>
    </ul>

  </nav>

  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="sidebar navbar-nav ">
      <li class="nav-item active">
        <a class="nav-link" href="index.html">
          <i class="fas fa-fw fa-plus-square"></i>
          <span>Create Project</span>
        </a>
      </li>
    </ul>

    <div id="content-wrapper">

      <div class="container-fluid">

        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="#">Create Project</a>
          </li>
          <li class="breadcrumb-item active">Overview</li>
        </ol>

        <!-- Icon Cards-->
        
        <form method="post" action="/project" class="post-form">
          {% csrf_token %}
          <label for="project_name">Choose Project</label>
          <select id="id_project_name" name="project_name" style="height: 30px;">
            <option value="myo">myo</option>
            <option value="leap">leap</option>
            <option value="voice">voice</option>
          </select>
          <button type="submit" class="btn-primary">create</button>
      </form>
    </br>
        <!-- DataTables Example -->
        <div class="card mb-3">
          <div class="card-header">
            <i class="fas fa-table"></i>
            Project table</div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <th>User</th>
                    <th>project name</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                {% for project in projects %}
                  <tr>
                    <td>{{ project.id_user.name }}</td>
                    <td>{{ project.project_name }}</td>
                    <td><center><a class="btn btn-primary getToken" data-id="{{ project.id }}" data-toggle="modal" data-target="#tokenModal" style="color: floralwhite;">Generate token</a></center></td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>

      </div>
      <!-- /.container-fluid -->

      

    </div>
    <!-- /.content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- token Modal-->
  <div class="modal fade" id="tokenModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content" >
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">TOKEN</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <textarea id=id-textarea style="height: 100px;margin: 10px;"></textarea>
        <div class="modal-footer">
        </div>
      </div>
    </div>
  </div>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="viewLogoutUser">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="/static/vendor/jquery/jquery.min.js"></script>
  <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="/static/vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Page level plugin JavaScript-->
  <script src="/static/vendor/chart.js/Chart.min.js"></script>
  <script src="/static/vendor/datatables/jquery.dataTables.js"></script>
  <script src="/static/vendor/datatables/dataTables.bootstrap4.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="/static/js/sb-admin.min.js"></script>

  <!-- Demo scripts for this page-->
  <script src="/static/js/getToken.js"></script>
  <script src="/static/js/demo/datatables-demo.js"></script>
  <script src="/static/js/demo/chart-area-demo.js"></script>

</body>
{% endblock %}

project/templates/login.html
{% extends "base.html" %}

{% block title %}Login Page{% endblock %}

{% block links %}
<!-- Custom fonts for this template-->
<link href="/static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

<!-- Custom styles for this template-->
<link href="/static/css/sb-admin.css" rel="stylesheet">
{% endblock %}
{% block body %}
<body class="bg-dark">

  <div class="container">
    <div class="card card-login mx-auto mt-5">
      <div class="card-header">Login Form</div>
      <div class="card-body">
        <p style="color: crimson;"> {{ warning }} </p>
        <p style="color: rgb(20, 245, 31);"> {{ warning1 }} </p>
        <form method="post" action="/login" class="post-form">
            {% csrf_token %}
          <div class="form-group">
            Email
            <div class="form-label-group">
              {{ form.email }}
            </div>
          </div>
          <div class="form-group">
            Password
            <div class="form-label-group">
              {{ form.password }}
            </div>
          </div>
          <button class="btn btn-primary btn-block" type="submit">Login</button>
        </form>
        <div class="text-center">
          <a class="d-block small mt-3" href="/viewRegister">Register an Account</a>
        </div>
      </div>
    </div>
  </div>

  <script>
    document.getElementById("id_email").classList.add("form-control");
    document.getElementById("id_password").classList.add("form-control");
    document.getElementById("id_email").placeholder = "email";
    document.getElementById("id_password").placeholder = "Password";
    document.getElementById("id_email").type = "text";
    document.getElementById("id_password").type = "password";
    document.getElementById("id_email").required = "required";
    document.getElementById("id_password").required = "required";
    document.getElementById("id_email").autofocus = "autofocus";
  </script>
  <!-- Bootstrap core JavaScript-->
  <script src="/static/vendor/jquery/jquery.min.js"></script>
  <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="/static/vendor/jquery-easing/jquery.easing.min.js"></script>

</body>
{% endblock %}

project/templates/loginUser.html
{% extends "base.html" %}

{% block title %}Login Page{% endblock %}

{% block links %}
<!-- Custom fonts for this template-->
<link href="/static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

<!-- Custom styles for this template-->
<link href="/static/css/sb-admin.css" rel="stylesheet">
{% endblock %}
{% block body %}
<body class="bg-dark">

  <div class="container">
    <div class="card card-login mx-auto mt-5">
      <div class="card-header">Login Form</div>
      <div class="card-body">
        <p style="color: crimson;"> {{ warning }} </p>
        <p style="color: rgb(20, 245, 31);"> {{ warning1 }} </p>
        <form method="post" action="/loginUser" class="post-form">
            {% csrf_token %}
          <div class="form-group">
            Email
            <div class="form-label-group">
              {{ form.email }}
            </div>
          </div>
          <div class="form-group">
            Password
            <div class="form-label-group">
              {{ form.password }}
            </div>
          </div>
          <button class="btn btn-primary btn-block" type="submit">Login</button>
        </form>
        <div class="text-center">
          <a class="d-block small mt-3" href="/viewRegisterUser">Register an Account</a>
        </div>
      </div>
    </div>
  </div>

  <script>
    document.getElementById("id_email").classList.add("form-control");
    document.getElementById("id_password").classList.add("form-control");
    document.getElementById("id_email").placeholder = "email";
    document.getElementById("id_password").placeholder = "Password";
    document.getElementById("id_email").type = "text";
    document.getElementById("id_password").type = "password";
    document.getElementById("id_email").required = "required";
    document.getElementById("id_password").required = "required";
    document.getElementById("id_email").autofocus = "autofocus";
  </script>
  <!-- Bootstrap core JavaScript-->
  <script src="/static/vendor/jquery/jquery.min.js"></script>
  <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="/static/vendor/jquery-easing/jquery.easing.min.js"></script>

</body>
{% endblock %}

project/templates/register.html
{% extends "base.html" %}

{% block title %}Register Page{% endblock %}

{% block links %}
<!-- Custom fonts for this template-->
<link href="/static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

<!-- Custom styles for this template-->
<link href="/static/css/sb-admin.css" rel="stylesheet">
{% endblock %}
{% block body %}
<body class="bg-dark">

  <div class="container">
    <div class="card card-login mx-auto mt-5">
      <div class="card-header">Register Form</div>
      <div class="card-body">
        <p style="color: crimson;"> {{ warning }} </p>
        <form method="post" action="/register" class="post-form">
            {% csrf_token %}
            <div class="form-group">
              Name
              <div class="form-label-group">
                {{ form.name }}
              </div>
            </div>
          <div class="form-group">
            Email   
            <div class="form-label-group">
              {{ form.email }}
            </div>
          </div>
          <div class="form-group">
            Password
            <div class="form-label-group">
              {{ form.password }}
            </div>
          </div>
          <button class="btn btn-primary btn-block" type="submit">Sign Up</button>
        </form>
        <div class="text-center">
        </div>
      </div>
    </div>
  </div>

  <script>
    document.getElementById("id_email").classList.add("form-control");
    document.getElementById("id_name").classList.add("form-control");
    document.getElementById("id_password").classList.add("form-control");
    document.getElementById("id_email").placeholder = "email";
    document.getElementById("id_password").placeholder = "Password";
    document.getElementById("id_email").type = "text";
    document.getElementById("id_name").type = "text";
    document.getElementById("id_password").type = "password";
    document.getElementById("id_email").required = "required";
    document.getElementById("id_name").required = "required";
    document.getElementById("id_password").required = "required";
    document.getElementById("id_name").autofocus = "autofocus";
    document.getElementById("id_email").autofocus = "autofocus";
  </script>
  <!-- Bootstrap core JavaScript-->
  <script src="/static/vendor/jquery/jquery.min.js"></script>
  <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="/static/vendor/jquery-easing/jquery.easing.min.js"></script>

</body>
{% endblock %}

project/templates/registerUser.html
{% extends "base.html" %}

{% block title %}Register Page{% endblock %}

{% block links %}
<!-- Custom fonts for this template-->
<link href="/static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

<!-- Custom styles for this template-->
<link href="/static/css/sb-admin.css" rel="stylesheet">
{% endblock %}
{% block body %}
<body class="bg-dark">

  <div class="container">
    <div class="card card-login mx-auto mt-5">
      <div class="card-header">Register Form</div>
      <div class="card-body">
        <p style="color: crimson;"> {{ warning }} </p>
        <form method="post" action="/registerUser" class="post-form">
            {% csrf_token %}
            <div class="form-group">
              Name
              <div class="form-label-group">
                {{ form.name }}
              </div>
            </div>
          <div class="form-group">
            Email   
            <div class="form-label-group">
              {{ form.email }}
            </div>
          </div>
          <div class="form-group">
            Password
            <div class="form-label-group">
              {{ form.password }}
            </div>
          </div>
          <button class="btn btn-primary btn-block" type="submit">Sign Up</button>
        </form>
        <div class="text-center">
        </div>
      </div>
    </div>
  </div>

  <script>
    document.getElementById("id_email").classList.add("form-control");
    document.getElementById("id_name").classList.add("form-control");
    document.getElementById("id_password").classList.add("form-control");
    document.getElementById("id_email").placeholder = "email";
    document.getElementById("id_password").placeholder = "Password";
    document.getElementById("id_email").type = "text";
    document.getElementById("id_name").type = "text";
    document.getElementById("id_password").type = "password";
    document.getElementById("id_email").required = "required";
    document.getElementById("id_name").required = "required";
    document.getElementById("id_password").required = "required";
    document.getElementById("id_name").autofocus = "autofocus";
    document.getElementById("id_email").autofocus = "autofocus";
  </script>
  <!-- Bootstrap core JavaScript-->
  <script src="/static/vendor/jquery/jquery.min.js"></script>
  <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="/static/vendor/jquery-easing/jquery.easing.min.js"></script>

</body>
{% endblock %}